// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-g8yOOSxhsYS5bGKaAQo31liODFXtk_w',
    appId: '1:266926054695:web:34f8b6f1976fb2384d9d02',
    messagingSenderId: '266926054695',
    projectId: 'auth-river',
    authDomain: 'auth-river.firebaseapp.com',
    storageBucket: 'auth-river.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa4lmr6zKiuSaGtWyjJZwmnbWL8BTw4j0',
    appId: '1:266926054695:android:cd2d18e18f0b28d74d9d02',
    messagingSenderId: '266926054695',
    projectId: 'auth-river',
    storageBucket: 'auth-river.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKScV6hT2GEIyIypQopH1qO2NpKYgI6ws',
    appId: '1:266926054695:ios:54fd58ebfaa59d5e4d9d02',
    messagingSenderId: '266926054695',
    projectId: 'auth-river',
    storageBucket: 'auth-river.firebasestorage.app',
    iosBundleId: 'com.example.fbAuthRiverpod',
  );

}